/*
 * test.java
 *
 * Created on 11 July 2008, 11:59
 */

package hemisphere;

/**
 *
 * @author  nicolas
 */
public class test extends javax.swing.JPanel {
    
    /** Creates new form test */
    public test() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        checkbox1 = new java.awt.Checkbox();
        checkbox2 = new java.awt.Checkbox();

        checkbox1.setLabel("Show angles");
        add(checkbox1);

        checkbox2.setLabel("Show circles");
        add(checkbox2);

    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Checkbox checkbox1;
    private java.awt.Checkbox checkbox2;
    // End of variables declaration//GEN-END:variables
    
}
